---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: '使用 NAS 协议（NFS、SMB）和 SAN 协议（FC、iSCSI、NVMe）为 Proxmox 虚拟环境 (VE) 提供ONTAP存储。选择合适的协议特定步骤来配置 Proxmox VE 集群的共享存储。' 
---
= 了解 Proxmox VE 与NetApp ONTAP的存储协议
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用 NAS 协议（NFS、SMB）和 SAN 协议（FC、iSCSI、NVMe）为 Proxmox 虚拟环境 (VE) 提供ONTAP存储。选择合适的协议特定步骤来配置 Proxmox VE 集群的共享存储。

确保 Proxmox VE 主机具有 FC、以太网或其他受支持的接口，并通过电缆连接到交换机，从而与ONTAP逻辑接口通信。务必检查 https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"] 适用于支持的配置。示例场景的创建基于以下假设：每个 Proxmox VE 主机上都有两张高速网络接口卡，这两张卡连接在一起以创建绑定接口，从而实现容错和性能。所有网络流量（包括主机管理、虚拟机/容器流量和存储访问）均使用相同的上行链路连接。当有更多网络接口可用时，考虑将存储流量与其他类型的流量分开。

有关ONTAP存储架构和支持的存储类型的信息，请参阅 link:proxmox-ontap-architecture.html["了解 Proxmox VE 的ONTAP存储架构"] 和 link:proxmox-storage-types.html["了解 Proxmox VE 支持的存储类型"]。


NOTE: 当使用 LVM 和 SAN 协议（FC、iSCSI、NVMe-oF）时，卷组可以包含多个 LUN 或 NVMe 命名空间。在这种情况下，所有 LUN 或命名空间都必须属于同一个一致性组，以确保数据完整性。我们不支持跨越多个ONTAP SVM 的卷组。每个卷组必须由同一 SVM 中的 LUN 或命名空间创建。



== 选择存储协议

选择符合您环境和要求的协议：

* link:proxmox-ontap-smb.html["配置 SMB/CIFS 存储"] - 为 Proxmox VE 配置 SMB/CIFS 文件共享，支持多通道，以实现容错和增强多网络连接的性能。
* link:proxmox-ontap-nfs.html["配置 NFS 存储"] - 使用 nConnect 或会话中继为 Proxmox VE 配置 NFS 存储，以实现容错和使用多个网络连接提升性能。
* link:proxmox-ontap-fc.html["使用 FC 配置 LVM"] - 配置逻辑卷管理器 (LVM) 与光纤通道，以实现跨 Proxmox VE 主机的高性能、低延迟块存储访问。
* link:proxmox-ontap-iscsi.html["配置 LVM 与 iSCSI"] - 配置逻辑卷管理器 (LVM) 与 iSCSI，以便通过支持多路径的标准以太网访问块存储。
* link:proxmox-ontap-nvme-fc.html["配置 LVM 与 NVMe/FC"] - 使用现代 NVMe 协议，通过光纤通道配置逻辑卷管理器 (LVM) 和 NVMe，以实现高性能块存储。
* link:proxmox-ontap-nvme-tcp.html["配置 LVM 与 NVMe/TCP"] - 使用现代 NVMe 协议，通过 TCP 配置逻辑卷管理器 (LVM) 和 NVMe，以便在标准以太网网络上实现高性能块存储。

