---
sidebar: sidebar 
permalink: euc/euc-overview.html 
keywords: euc, digital workspace, virtual desktop, vdi, virtual desktop infrastructure, cloud desktop, virtual application, application virtualization, app virtualization, virtual desktop management, desktop management, application management 
summary:  
---
= 了解最终用户计算与 NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
最终用户计算 (EUC) 是一种允许用户从任何设备、任何地点访问其桌面和应用程序的技术。采用 NetApp 的 EUC 解决方案包括虚拟桌面基础架构 (VDI)、应用程序虚拟化和用户配置文件管理。借助 NetApp 的 EUC 解决方案，组织可以提高生产力、降低成本并增强最终用户的安全性。



== 什么是最终用户计算 (EUC)？

最终用户计算 (EUC) 是一种技术，允许用户从任何地方的任何设备访问其桌面和应用程序。EUC 解决方案通常包括虚拟桌面基础架构 (VDI)、应用虚拟化和用户配置文件管理工具。借助 EUC，组织可以提高生产力、降低成本并增强最终用户的安全性。文件共享和主目录也是 EUC 解决方案的一部分，使用户可以从任何设备访问其文件和数据。

用户需要通过单个应用程序或完整桌面访问应用程序来执行其工作。某些用户可能需要高端图形应用程序用于其桌面工作流或特定应用程序用例。采用 NetApp 的 EUC 解决方案可以根据每个用户的需求和要求为他们提供合适的解决方案。借助 NetApp 的 EUC 解决方案，组织可以为用户提供从任何地点的任何设备访问其桌面和应用程序的权限，同时确保安全高效地存储数据。

组织可以选择在本地、云或混合环境中部署 EUC 解决方案，使他们能够灵活地选择最适合其需求的部署模式。借助 NetApp 的 EUC 解决方案，组织可以提高最终用户的生产力、降低成本并提高其安全性，同时还为他们提供在任何地方工作的灵活性。



== 使用 NetApp 进行最终用户计算的高级优势

NetApp 的 EUC 解决方案为组织提供了多项优势，包括：* 提高生产力：借助 EUC，用户可以从任何地方的任何设备访问其桌面和应用程序，从而提高生产力和协作。* 降低成本：EUC 可以通过集中桌面和应用程序管理来帮助组织降低成本，从而减少对昂贵硬件和软件的需求。* 增强安全性：EUC 可以通过集中桌面和应用程序管理来帮助组织增强安全性，从而降低数据泄露和其他安全事件的风险。* 可扩展性：NetApp 的 EUC 解决方案具有可扩展性，允许组织根据需要轻松添加或删除用户。* 灵活性：NetApp 的 EUC 解决方案可以部署在本地、云或混合环境中，使组织能够灵活地选择最适合其需求的部署模式。

有关详细信息，请查看 link:euc-benefits.html["NetApp 存储对最终用户计算的好处"] 页面。



== NetApp 的 EUC 解决方案

NetApp 提供一系列 EUC 解决方案，包括：* 虚拟桌面基础设施 (VDI)：VDI 解决方案使组织能够向最终用户提供虚拟桌面，使他们能够从任何地方的任何设备访问其桌面和应用程序。* 应用程序虚拟化：应用程序虚拟化解决方案允许组织向其最终用户交付虚拟应用程序，使他们能够从任何地方的任何设备访问其应用程序。* 文件共享和主目录：文件共享和主目录解决方案允许组织为用户提供从任何地点的任何设备访问其文件和数据的权限，同时确保安全高效地存储数据。* 用户配置文件管理：用户配置文件管理解决方案允许组织跨多个设备管理用户配置文件和设置，为用户提供一致的体验，无论他们使用的设备是什么。
