---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 使用基于 FC 的 VMFS 数据存储在 ONTAP 上作为 VCF 工作负载域的主存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此用例中，我们概述了在 ONTAP 上设置光纤通道 (FC) VMFS 数据存储的过程，将其作为 VMware Cloud Foundation (VCF) 工作负载域的主要存储解决方案。此过程总结了所需的组件、配置步骤和部署过程。



[[benefits-of-fibre-channel]]
== 光纤通道的优势

*高性能：* FC 提供高速数据传输速率，使其成为需要快速可靠地访问大量数据的应用程序的理想选择。

*低延迟*：非常低的延迟，这对于数据库和虚拟化环境等性能敏感的应用程序至关重要。

*可靠性：*FC 网络以其稳健性和可靠性而闻名，具有内置冗余和纠错等功能。

*专用带宽：* FC 为存储流量提供专用带宽，降低网络拥塞的风险。

有关使用光纤通道与NetApp存储系统的更多信息，请参阅 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["使用 FC 进行 SAN 配置"]。



[[scenario-overview]]
== 场景概述

此场景涵盖以下高级步骤：

* 创建具有逻辑接口 (LIF) 的存储虚拟机 (SVM) 用于 FC 流量。
* 收集待部署主机的WWPN信息，并在ONTAP存储系统上创建相应的启动器组。
* 在ONTAP存储系统上创建 FC 卷。
* 将启动器组映射到已创建的 FC 卷。
* 在 FC 交换机上利用单启动器-目标分区。为每个启动器创建一个区域（单启动器区域）。
+
** 对于每个区域，包括一个目标，即 SVM 的ONTAP FC 逻辑接口 (WWPN)。每个 SVM 每个节点应至少有两个逻辑接口。请勿使用物理端口的 WWPN。


* 在 vCenter 中为 vMotion 流量创建网络池。
* 在 vCenter 中调试主机以用于工作负载域。
* 使用 FC 数据存储区上的 VMFS 作为主存储，在 VCF Ops 中部署工作负载域。



NOTE: 此解决方案适用于支持 FC 存储的 ONTAP 平台，包括 NetApp ASAr2、AFF 和 FAS。



[[prerequisites]]
== 前提条件

此场景中使用以下组件和配置：

* 具有连接到 FC 交换机的 FC 端口的 ONTAP AFF、ASA 或 FAS 存储系统。
* 使用 FC lifs 创建的 SVM。
* 带有 FC HBA 的 vSphere 连接到 FC 交换机。
* 在 FC 交换机上配置单个启动器-目标分区。
* 确保 SVM 多路径策略设置为 active-active。



NOTE: NetApp建议对 FC LUN 使用多路径。



[[deployment-steps]]
== 部署步骤



[[vcf-workload-domain-default-cluster]]
=== VCF 工作负载域 - 默认集群

管理域启动并运行后，可以创建 VCF 工作负载域：

* 使用 VCF Ops UI。vSphere 主机在 vCenter 中调试完毕，并配置了网络池。使用 System Manager 或 ONTAP API 将 LUN 部署到 vSphere 主机。
* 将现有 vSphere 环境作为新工作负载域导入。ONTAP tools for VMware vSphere 或 System Manager 或 ONTAP API 可用于将 VMFS 数据存储部署到 vSphere 集群。




[[vcf-workload-domain-additional-cluster]]
=== VCF 工作负载域 - 附加集群

要使用其他群集扩展工作负载域，请参阅 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["向 VCF 域添加 SDDC 集群"]。

从整体上看，向工作负载域添加其他集群的步骤如下： * 确保主机已调试完成，并在 vCenter 中配置了网络池。* LUN 在 ONTAP 存储系统上进行配置，并呈现给附加集群中的主机。* 在 vCenter 上的工作负载域中创建新的 SDDC 集群，然后按照向导将附加集群添加到工作负载域。



[[additional-information]]
== 追加信息

有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 云基础文档"]。
