---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= 了解如何使用适用ONTAP tools for VMware vSphere管理虚拟机
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere简化了使用NetApp存储的虚拟机的生命周期管理。管理员可以直接从 vCenter Server 管理存储，从而简化操作并增强可扩展性。虚拟存储控制台 (VSC)、VASA 提供程序和存储复制适配器 (SRA) 等关键组件可优化配置、性能监控和灾难恢复。



== 简介

它使管理员能够直接管理 vCenter Server 内的存储，并简化 VMware 环境的存储和数据管理。 VMware vSphere Client 插件工具旨在将插件功能集成到 vSphere Client 中，而无需在 vCenter Server 内部运行。这提供了插件隔离并支持在大型 vSphere 环境中运行的插件的横向扩展。



== ONTAP工具组件

* *虚拟存储控制台 (VSC)* VSC 包括与 vSphere 客户端集成的界面，您可以在其中添加存储控制器、配置数据存储库、监控数据存储库的性能以及查看和更新 ESXi 主机设置。
* *VASA 提供程序* 适用于ONTAP 的VMware vSphere APIs for Storage Awareness (VASA) 提供程序将有关 VMware vSphere 使用的存储的信息发送到 vCenter Server，从而实现 VMware 虚拟卷 (vVols) 数据存储的配置、存储功能配置文件的创建和使用、合规性验证以及性能监控。
* *存储复制适配器 (SRA)* 启用并与 VMware Site Recovery Manager (SRM) 一起使用时，SRA 可在发生故障时促进 vCenter Server 数据存储和虚拟机的恢复，从而允许配置受保护站点和恢复站点以进行灾难恢复。


有关适用于 VMware 的NetApp ONTAP工具的更多信息，请参阅 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP tools for VMware vSphere文档"]。
