---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-security.html 
keywords:  
summary:  
---
= 了解如何降低 VMware 工作负载的安全和勒索软件风险
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP通过加密、快照和高级访问控制增强了 VMware 环境中的安全性和勒索软件防护，补充了 VMware 的安全功能以保护数据。



== 简介

通过在 VMware 环境中利用NetApp ONTAP的高级功能，组织可以确保其数据的完整性、可用性和安全性。

请参阅下文，详细了解这些技术如何协同工作以提供*安全*和*备份优势*。



== 安全和勒索软件

安全性是虚拟化环境中的首要关注点，而NetApp ONTAP提供了强大的功能来增强 VMware 基础架构内的安全性。 ONTAP为静态数据和传输中的数据提供加密，确保敏感信息免遭未经授权的访问。加密密钥得到安全管理，并且ONTAP支持基于软件和基于硬件的加密解决方案。通过与 VMware 的安全工具（例如 vSphere 的内置安全功能和第三方安全解决方案）集成， ONTAP有助于创建安全且合规的环境。



== 勒索软件防御

勒索软件攻击对组织构成重大威胁，而 VMware 与ONTAP的结合提供了强大的防御机制。 ONTAP 的快照技术允许创建不可变的快照，勒索软件无法更改或删除。如果发生攻击，这些快照可用于快速将受影响的虚拟机和数据存储恢复到攻击前的状态，从而最大限度地减少停机时间和数据丢失。此外，ONTAP 与安全信息和事件管理 (SIEM) 系统的集成实现了对可疑活动的主动监控和警报。  ONTAP还支持多因素身份验证 (MFA) 和基于角色的访问控制 (RBAC)，以进一步增强安全性。



== 勒索软件恢复保证

NetApp勒索软件保障为组织提供了强大而可靠的解决方案，以防止勒索软件攻击。通过利用NetApp ONTAP的先进功能，组织可以确保其数据的安全性和可用性。该保证让您安心，因为您知道，如果发生勒索软件攻击，数据可以快速有效地恢复，最大限度地减少停机时间、数据丢失和财务影响。对数据安全和弹性的承诺使NetApp成为希望保护其关键资产免受不断演变的网络威胁的组织的理想合作伙伴。



== 高级安全功能

ONTAP包括高级安全功能，例如安全多租户（可在多租户环境中隔离数据和资源）和合规性审计（可跟踪和记录对敏感数据的访问）。这些功能可确保数据安全，并且组织可以证明符合行业法规和标准。



== 摘要

ONTAP 的安全功能（例如加密、不可变快照和高级访问控制）与 VMware 工具的集成提供了对包括勒索软件在内的网络威胁的强大防御。  ONTAP 对安全多租户和合规性审计的支持可确保数据保护和法规遵从性。

NetApp ONTAP和 VMware 共同提供了用于保护虚拟化环境的全面解决方案，使组织能够保护数据、最大限度地减少停机时间并保持业务连续性。实施这些技术有助于企业应对现代 IT 挑战并保护关键资产免受不断演变的安全威胁。
