---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-supp-nfs-vvols-network.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, vvol, vvols, array, ontap tools, otv, sddc 
summary: 在 VMware Cloud Foundation 管理域中的 ESXi 主机上配置 NFS 网络以实现与ONTAP存储系统的连接。您将创建具有 VLAN 分离的分布式端口组，配置上行链路组合以实现冗余，并在每个 ESXi 主机上设置 VMkernel 适配器以建立专用的 NFS 路径来实现故障转移功能。 
---
= 在 VCF VI 工作负载域中的 ESXi 主机上配置 NFS 网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在 VMware Cloud Foundation 管理域中的 ESXi 主机上配置 NFS 网络以实现与ONTAP存储系统的连接。您将创建具有 VLAN 分离的分布式端口组，配置上行链路组合以实现冗余，并在每个 ESXi 主机上设置 VMkernel 适配器以建立专用的 NFS 路径来实现故障转移功能。

使用 vSphere 客户端在 VI 工作负载域集群上执行以下步骤。在这种情况下，使用 vCenter Single Sign-On，因此 vSphere 客户端在管理和工作负载域中是通用的。



== 步骤 1：为 NFS 流量创建分布式端口组

完成以下步骤，为网络创建一个新的分布式端口组来承载 NFS 流量。

.步骤
. 从 vSphere 客户端，导航到工作负载域的 *Inventory > Networking*。导航到现有的分布式交换机并选择创建*新分布式端口组...*的操作。
. 在“新建分布式端口组”向导中，填写新端口组的名称，然后单击“下一步”继续。
. 在*配置设置*页面上，填写所有设置。如果正在使用 VLAN，请确保提供正确的 VLAN ID。单击“*下一步*”继续。
. 在*准备完成*页面上，检查更改并单击*完成*以创建新的分布式端口组。
. 创建端口组后，导航到该端口组并选择操作*编辑设置...*。
. 在*分布式端口组 - 编辑设置*页面上，导航到左侧菜单中的*组合和故障转移*。确保上行链路位于“活动上行链路”区域中，以启用用于 NFS 流量的上行链路组合。将任何未使用的上行链路移至*未使用的上行链路*。
. 对群集中的每个 ESXi 主机重复此过程。




== 步骤 2：在每个 ESXi 主机上创建 VMkernel 适配器

在工作负载域中的每个 ESXi 主机上创建一个 VMkernel 适配器。

.步骤
. 从 vSphere 客户端导航到工作负载域清单中的其中一个 ESXi 主机。从*配置*选项卡中选择*VMkernel 适配器*，然后单击*添加网络...*开始。
. 在*选择连接类型*窗口中，选择*VMkernel 网络适配器*，然后单击*下一步*继续。
. 在“选择目标设备”页面上，选择之前创建的 NFS 分布式端口组之一。
. 在*端口属性*页面上，保留默认设置（未启用服务）并单击*下一步*继续。
. 在 *IPv4 设置* 页面上，填写 *IP 地址*、*子网掩码*，并提供新的网关 IP 地址（仅在需要时）。单击“*下一步*”继续。
. 在*准备完成*页面上检查您的选择，然后单击*完成*以创建 VMkernel 适配器。




== 下一步是什么？

在工作负载域中的所有 ESXi 主机上配置 NFS 网络后，link:vmw-vcf-viwld-supp-nfs-vvols-storage.html["为 NFS vVols配置存储"] 。
