---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: 查看将具有NetApp ONTAP NFS 数据存储区的 vSphere 8 集群转换为 VMware Cloud Foundation 管理域的要求。 
---
= 使用 NFS 数据存储将 vCenter Server 实例转换为 VCF 管理域的部署要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
查看将具有NetApp ONTAP NFS 数据存储区的 vSphere 8 集群转换为 VMware Cloud Foundation 管理域的要求。

转换过程需要AFF或ASA存储系统、用于 FC 流量的 SVM 和 LIF、交换机上的 NFS 分区、带有 ESXi 主机和 vCenter 的 vSphere 集群以及用于 vMotion 的专用网络段。



== 基础设施要求

确保以下组件和配置已到位。

* NetApp AFF存储系统，其存储虚拟机 (SVM) 配置为允许 NFS 流量。
* 在 IP 网络上创建的用于承载 NFS 流量并与 SVM 关联的逻辑接口 (LIF)。
* 一个 vSphere 集群，其中包含 4 个 ESXi 主机和一个位于该集群上的 vCenter 设备。
* 为 vMotion 和 NFS 存储流量在为此目的建立的 VLAN 或网络段上配置的分布式端口组。
* VCF 转换软件。对于所需的软件，请访问 https://support.broadcom.com/["Broadcom 支持门户"]。
* ONTAP工具的先决条件。
+
有关ONTAP工具前提条件的完整信息，请参阅 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["适用于ONTAP tools for VMware vSphere的先决条件"]。

+
ONTAP tools for VMware vSphere可以安装在 HA 或非 HA 配置中。





== 其他资源

* 有关将 vSphere 转换或导入 VCF 5.2 时支持的存储和其他注意事项，请参阅 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/considerations-before-converting-or-importing-existing-vsphere-environments-into-vcf-admin.html["将现有 vSphere 环境转换或导入 VMware Cloud Foundation 之前的注意事项"]。
* 有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]。
* 有关配置 VCF 的信息，请参阅link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation 5.2 文档"]。




== 下一步是什么？

查看部署要求后，link:vmw-vcf-mgmt-nfs-deploy.html["部署ONTAP工具并配置 NFS 数据存储库"] 。
