---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 使用ONTAP上基于 FC 的 VMFS 数据存储库作为 VCF 管理域的主要存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此用例中，我们概述了在 ONTAP 上创建基于 FC 的 VMFS 数据存储区的步骤，该数据存储区作为 VMware Cloud Foundation (VCF) 管理域的主存储。此过程总结了所需的组件、配置和部署步骤。



[[introduction]]
== 简介

在适当的情况下，我们将参考外部文档以了解必须在 vCenter 中执行的步骤，并参考特定于存储配置部分的步骤。

有关使用 ONTAP 在 vSphere 环境中转换现有 VMFS 数据存储区（包括 iSCSI 和 NVMe-oF）的信息，请参阅 link:vmw-vcf-mgmt-vmfs.html["将 vSphere 环境（VMFS 数据存储）融合到 VCF 管理域"]。


NOTE: VCF 版本 5.2 引入了将现有 vSphere 8 环境转换为 VCF 管理域或作为 VCF VI 工作负载域导入的功能。在此版本之前，VMware vSAN 是 VCF 管理域的唯一主体存储选项。NSX 控制器 VM 更适合部署在基于 FC 的 VMFS 数据存储上，或使用双网络交换机以避免单点故障。如果这些选项不可用，请考虑使用 vSAN 来托管这些虚拟机。


NOTE: 该解决方案适用于支持FC存储的ONTAP平台，包括NetApp ASA、 AFF和FAS。



[[prerequisites]]
== 前提条件

此场景中使用以下组件和配置：

* NetApp存储系统配置了存储虚拟机 (SVM) 以允许 FC 流量。
* 已在 FC 结构上创建用于承载 FC 流量并与 SVM 关联的逻辑接口 (LIF)。
* 分区已配置为在 FC 交换机上使用单个启动器-目标分区，用于主机 HBA 和存储目标。


有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 云基础文档"]。



[[deployment-steps]]
== 部署步骤



[[management-domain-default-cluster]]
=== 管理域 - 默认集群

VCF Installer tool 支持管理域的 FC、NFS v3 和 vSAN 数据存储上的 VMFS。以下步骤概述了使用基于 FC 的 VMFS 数据存储（位于 ONTAP 上）作为主存储来部署管理域的过程。

有关使用现有 vSphere 环境的更多信息，请参阅 link:vmw-vcf-mgmt-vmfs.html["将 vSphere 环境（VMFS 数据存储）融合到 VCF 管理域"]。



[[management-domain-additional-cluster]]
=== 管理域 - 附加集群

要使用其他群集扩展管理域，请参阅 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["向 VCF 域添加 SDDC 集群"]。

在高层面上，向管理域添加其他集群的步骤如下：* 确保主机已调试完毕，并在 vCenter 中配置了网络池。* LUN 已在 ONTAP 存储系统上进行配置，并呈现给其他集群中的主机。* 在 vCenter 上的管理域中创建新的 SDDC 集群，然后按照向导将其他集群添加到管理域。



[[additional-information]]
== 追加信息

有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 云基础文档"]。
