---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 使用ONTAP上基于 FC 的 VMFS 数据存储库作为 VCF 管理域的主要存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此用例中，我们概述了使用ONTAP上现有的基于 FC 的 VMFS 数据存储作为 VMware Cloud Foundation (VCF) 管理域的主存储的过程。此过程总结了所需的组件、配置和部署步骤。



== 简介

在适当的情况下，我们将参考外部文档，了解必须在 VCF 的 SDDC 管理器中执行的步骤，并参考特定于存储配置部分的步骤。

有关使用ONTAP转换现有基于 FC 的 vSphere 环境的信息，请参阅link:vmw-vcf-mgmt-fc.html["将 vSphere 环境（FC 数据存储）转换为 VCF 管理域"]。


NOTE: VCF 版本 5.2 引入了将现有 vSphere 8 环境转换为 VCF 管理域或导入为 VCF VI 工作负载域的功能。在此版本之前，VMware vSAN 是 VCF 管理域的主要存储的唯一选项。


NOTE: 该解决方案适用于支持FC存储的ONTAP平台，包括NetApp ASA、 AFF和FAS。



== 前提条件

此场景中使用以下组件和配置：

* NetApp存储系统配置了存储虚拟机 (SVM) 以允许 FC 流量。
* 已在 FC 结构上创建用于承载 FC 流量并与 SVM 关联的逻辑接口 (LIF)。
* 分区已配置为在 FC 交换机上使用单个启动器-目标分区，用于主机 HBA 和存储目标。


有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware 云基础文档"]。



== 部署步骤



=== 管理域 - 默认集群

初始集群上的 FC 主存储仅支持 VCF 棕地导入工具。如果使用 Cloud Builder 工具（版本 5.2.x 之前的版本）部署 VCF，则仅支持 vSAN。

有关使用现有 vSphere 环境的更多信息，请参阅 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["将现有 vSphere 环境转换为管理域"]了解更多信息。



=== 管理域 - 附加集群

管理域上的附加 vSphere 集群可以通过以下选项进行部署：

* 在 vSphere 环境中拥有额外的集群，并使用 VCF 棕地导入工具将 vSphere 环境转换为管理域。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["适用于 VMware vSphere 的 ONTAP 工具"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["系统管理器或ONTAP API"]可用于将 VMFS 数据存储部署到 vSphere 集群。
* 使用 SDDC API 部署额外的集群。 vSphere 主机应该配置 VMFS 数据存储。使用 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["系统管理器或ONTAP API"]将 LUN 部署到 vSphere 主机。
* 使用 SDDC Manager UI 部署额外的集群。但此选项仅创建 VSAN 数据存储至 5.2.x 版本。




== 追加信息

有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware 云基础文档"]。
