---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: 查看将包含 NetApp ONTAP NFS 数据存储的 vSphere 集群融合到 VMware Cloud Foundation 管理域的要求。 
---
= 使用 NFS 数据存储将 vCenter 服务器实例融合到 VCF 管理域的部署要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
查看将包含 NetApp ONTAP NFS 数据存储的 vSphere 集群融合到 VMware Cloud Foundation 管理域的要求。

融合过程需要 AFF 或 AFX 存储系统、用于 NFS 流量的 SVM 和 LIF、交换机上的 NFS VLAN、一个包含 vSphere 主机和 vCenter 的 vSphere 集群，以及用于 vMotion 的专用网段。



[[infrastructure-requirements]]
== 基础设施要求

确保以下组件和配置已到位。

* NetApp AFF 或 AFX 存储系统，具有配置为允许 NFS 流量的 Storage Virtual Machine (SVM)。
* 在 IP 网络上创建的用于承载 NFS 流量并与 SVM 关联的逻辑接口 (LIF)。
* 一个至少包含 2 台 vSphere 主机的 vSphere 集群，以及一台与集群共存的 vCenter 设备。
* 为 vMotion 和 NFS 存储流量在为此目的建立的 VLAN 或网络段上配置的分布式端口组。
* 用于将 vCenter 融合到 VCF 管理域的 VCF 安装程序工具。
* ONTAP工具的先决条件。
+
有关ONTAP工具前提条件的完整信息，请参阅 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["适用于ONTAP tools for VMware vSphere的先决条件"]。

+
ONTAP tools for VMware vSphere可以安装在 HA 或非 HA 配置中。





[[additional-resources]]
== 其他资源

* 要了解支持的存储和将 vSphere 收敛到 VCF 的其他注意事项，请参阅 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["支持和不支持融合到 VCF 的配置"]。
* 有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]。
* 有关配置 VCF 的信息，请参见 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 9.1 文档"]。




[[whats-next]]
== 下一步是什么？

查看部署要求后，link:vmw-vcf-mgmt-nfs-deploy.html["部署ONTAP工具并配置 NFS 数据存储库"] 。
