---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= 使用ONTAP上的 NFS 数据存储库作为 VCF 管理域的主要存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此用例中，我们概述了在 ONTAP 上创建 NFS 数据存储作为 VMware Cloud Foundation (VCF) 管理域主存储的过程。此过程总结了所需的组件、配置步骤和部署过程。



[[introduction]]
== 简介

在适当的情况下，我们将参考外部文档以了解必须在 vCenter 中执行的步骤，并参考特定于存储配置部分的步骤。

如果需要将 NFS 4.1 数据存储用于主体存储，或者将基于 NFS 的现有 vSphere 环境转换为使用 ONTAP 的环境，请参阅 link:vmw-vcf-mgmt-nfs.html["将 vSphere 环境（NFS 数据存储）融合到 VCF 管理域"]。


NOTE: VCF 版本 5.2 引入了将现有 vSphere 8 环境转换为 VCF 管理域或作为 VCF VI 工作负载域导入的功能。在此版本之前，VMware vSAN 是 VCF 管理域的唯一主体存储选项。NSX 控制器 VM 更适合部署在基于 FC 的 VMFS 数据存储上，或使用双网络交换机以避免单点故障。如果这些选项不可用，请考虑使用 vSAN 来托管这些虚拟机。


NOTE: 此解决方案适用于支持 NFS 存储的 ONTAP 平台，包括 NetApp AFF、AFX 和 FAS。



[[prerequisites]]
== 前提条件

此场景中使用以下组件和配置：

* NetApp存储系统，其存储虚拟机 (SVM) 配置为允许 NFS 流量。
* 已在 IP 网络上创建用于承载 NFS 流量并与 SVM 关联的逻辑接口 (LIF)。
* 至少包含 2 个 vSphere 主机的 vSphere 集群。
* 挂载在其中一个 vSphere 主机上的 NFS 数据存储，使用与管理域相同的 NFS 服务器和导出路径。



NOTE: 部署 VCF 域时，VCF 会验证与 NFS 服务器的连接。这是在使用 NFS IP 地址添加任何其他 vmkernel 适配器之前，使用 vSphere 主机上的管理适配器完成的。因此，有必要确保以下任一条件：1）管理网络可路由到 NFS 服务器，或 2）已将管理网络的 LIF 添加到托管 NFS 数据存储卷的 SVM，以确保验证可以继续进行。

* 确保 ONTAP NFS VAAI 工具安装在其中一个可选择作为集群映像模板的 vSphere 主机上。
* 部署 VCF Installer 工具。


有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 云基础文档"]。



[[deployment-steps]]
== 部署步骤



[[management-domain-default-cluster]]
=== 管理域 - 默认集群

VCF Installer tool 支持管理域的 FC、NFS v3 和 vSAN 数据存储上的 VMFS。以下步骤概述了以基于 NFSv3 的 ONTAP 数据存储作为主存储来部署管理域的过程。


NOTE: 部署后验证或调整 NFS 数据存储区的 nConnect 值。

有关使用现有 vSphere 环境的更多信息，请参阅 link:vmw-vcf-mgmt-nfs.html["将 vSphere 环境（NFS 数据存储）融合到 VCF 管理域"]。



[[management-domain-additional-cluster]]
=== 管理域 - 附加集群

要使用其他群集扩展管理域，请参阅 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["向 VCF 域添加 SDDC 集群"]。

在高级别上，向管理域添加其他集群的步骤如下：* 确保主机已调试完毕，并在 vCenter 中配置了网络池。* NFS 数据存储卷在 ONTAP 存储系统上调配，并导出到其他集群中的主机。* 在 vCenter 上的管理域中创建新的 SDDC 集群，然后按照向导将附加集群添加到管理域。



[[additional-information]]
== 追加信息

有关配置ONTAP存储系统的信息，请参阅link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文档"]中心。

有关配置 VCF 的信息，请参阅 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 云基础文档"]。
