---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= 了解如何使用适用于 VMware vSphere 的SnapCenter插件备份和还原虚拟机
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere可对虚拟机、数据存储区和 VMDK 文件实现快速、虚拟机一致的备份和还原操作。此 VMware 插件与SnapCenter Server 集成，以支持基于应用程序的备份和SnapCenter特定应用程序插件的恢复。



== 文档资源

有关详细信息，请参阅以下文档资源。

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphere文档"]




== 解决方案资源

请参阅以下 3-2-1 备份解决方案，该方案包含SnapCenter Plug-in for VMware vSphere以及适用于虚拟机的NetApp备份和恢复功能。

技术报告：link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-321-dp-scv.html["使用SnapCenter插件和NetApp Backup and RecoveryVMware 的 3-2-1 数据保护"^]

Tech ONTAP博客：link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["使用SnapCenter插件和NetApp Backup and RecoveryVMware 的 3-2-1 数据保护"]



== 视频资源

.SnapCenter Plug-in for VMware vSphere- 解决方案先决条件
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in for VMware vSphere- 部署
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in for VMware vSphere- 备份工作流
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in for VMware vSphere- 还原工作流
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - SQL 还原工作流
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]