---
sidebar: sidebar 
permalink: openshift/osv-deployment-models.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift 虚拟化 
---
= OpenShift/OpenShift 虚拟化的部署模型
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
OpenShift 容器平台部署模型主要按其运行的基础设施（云与本地）以及管理方式（由 Red Hat 或客户管理）进行分类。OpenShift 虚拟化可以安装在 OpenShift 容器平台上。



[[key-deployment-models-include]]
== 主要部署模型包括

. **托管服务（Red Hat 托管）**：在此模型中，Red Hat 管理 OpenShift 容器平台基础设施和操作。客户负责在平台上管理其应用程序和工作负载。示例包括：
+
.. **Red Hat OpenShift Service on AWS (ROSA)**：一种允许轻松集成 AWS 服务的托管服务。OpenShift 虚拟化安装在 AWS 上的 EC2 裸机实例上。
.. **Azure Red Hat OpenShift (ARO)**：这是 Azure 云上的托管服务。OpenShift 虚拟化在 Azure 虚拟机之上运行。
.. **Red Hat OpenShift Dedicated (OSD)**：部署在 Google Cloud 上的完全托管服务，由 Red Hat 管理。OpenShift 虚拟化部署在 Google Cloud 裸机实例上。


. **自我管理服务（客户管理）**：在这种情况下，OpenShift 容器平台由客户在其自己的基础设施上直接部署和管理。基础架构可以是公共云或本地部署。
+
.. **公有云：** 使用安装程序预置的基础架构 (IPI) 或用户预置的基础架构 (UPI) 部署在 AWS、Azure 或 GCP 上
.. **裸机：**直接部署在物理硬件上。
.. **虚拟化：**部署在 VMware vSphere 等平台上。






[[infrastructure-deployment-options]]
=== 基础架构部署选项

. **安装程序提供的基础设施 (IPI)：** 安装程序自动提供基础设施组件，例如网络和机器。
. **用户预置的基础设施 (UPI)：** 用户手动创建和管理基础设施，从而对环境实现更多控制。




[[specialized-deployment-models]]
== 专业化部署模式

. **单节点 OpenShift（SNO）：** 安装在单个物理或虚拟机上的完整 OpenShift 集群，通常用于边缘计算。
. **断开连接（气隙）部署：**部署在没有外部互联网访问的受限网络环境中。
. **Red Hat OpenShift Virtualization Engine：**仅限裸机的虚拟化基础设施，专为企业提供可靠的企业级解决方案，用于部署、管理和扩展虚拟机。作为 OpenShift 功能的子集，此版本的 OpenShift 专为仅虚拟机工作负载而设计。




[[additional-resources]]
== 其他资源

有关 OpenShift 容器平台的完整详细信息，请参见 Red Hat link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/overview/ocp-overview["单击此处查看文档。"]

有关 OpenShift 虚拟化的完整详细信息，请参见 Red Hat link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/virtualization/index["单击此处查看文档。"]
